GET  http://127.0.0.1:8080/fuchsia/allposts
Content-Type:application/json


{
    "comment":"Keep in mind that this is your stored document. We have not called .populate() on it yet."
}


#########

GET http://127.0.0.1:8080/fuchsia/google_api


